pub mod agregar_estacion;
pub mod eleccion;
pub mod notificar_lider;
pub mod reenviar;
pub mod informar_venta;
pub mod aceptar_cliente;
pub mod transacciones_por_estacion;
pub mod confirmar_transacciones;
pub mod cobrar_a_cliente;
pub mod estacion_desconectada;
pub mod cambiar_conexion_listener;
mod habilitar_surtidor;
mod surtidor_libre;
mod identificar_estacion;
mod enviar_ventas_agrupadas;
mod empezar_informar_ventas_offline;
mod informar_ventas_offline;
mod procesar_mensaje;
mod liberar_clientes_en_cola;
mod enviar_a_siguiente;
mod lider_caido;
mod nuevo_lider_conectado;