pub mod aceptar_cliente;
pub mod agregar_estacion;
pub mod cambiar_conexion_listener;
pub mod cobrar_a_cliente;
pub mod confirmar_transacciones;
mod desconexion_detectada;
pub mod eleccion;
mod empezar_informar_ventas_offline;
mod enviar_a_siguiente;
mod enviar_ventas_agrupadas;
pub mod estacion_desconectada;
mod habilitar_surtidor;
mod identificar_estacion;
pub mod informar_venta;
mod informar_ventas_offline;
mod liberar_clientes_en_cola;
mod lider_caido;
pub mod notificar_lider;
mod nuevo_lider_conectado;
mod procesar_mensaje;
pub mod reenviar;
mod surtidor_libre;
pub mod transacciones_por_estacion;
