# Archivo usado unicamente para configurar los alias de los comandos de Cargo

[alias]

# Comandos de Cargo
linter = "clippy --verbose --all-targets --all-features"
compile = "build --release"
tests_integracion = "test --package tests_integracion --test estacion_test --test ypf_ruta_test"

# Se pueden agregar comandos personalizados
